<a href="https://colab.research.google.com/github/Gsmovidic/Entregable-2-Analisis-de-datos/blob/main/Notebook_AIRBNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Cargar datos

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arianazmoudeh/airbnbopendata")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'airbnbopendata' dataset.
Path to dataset files: /kaggle/input/airbnbopendata

In [5]:
df = pd.read_csv(
    path + '/Airbnb_Open_Data.csv',
    low_memory=False)
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [6]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

# Visualizamos todos los distintos distritos de NY city

In [9]:
df['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [12]:
df['neighbourhood group'].value_counts()

neighbourhood group
Manhattan        43792
Brooklyn         41842
Queens           13267
Bronx             2712
Staten Island      955
brookln              1
manhatan             1
Name: count, dtype: int64

# Limpieza de datos

# Corregir datos: brookln, manhatan

In [13]:
df['neighbourhood group'] = df['neighbourhood group'].replace({
    'brookln': 'Brooklyn',
    'manhatan': 'Manhattan'
})

In [14]:
df['neighbourhood group'].value_counts()

neighbourhood group
Manhattan        43793
Brooklyn         41843
Queens           13267
Bronx             2712
Staten Island      955
Name: count, dtype: int64

# Normalizar nombres columnas para que cuando haya espacio este un _

In [15]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

#  Limpiar price y service_fee

In [16]:
df['price'] = df['price'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)
df['service_fee'] = df['service_fee'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

# Convertir fechas

In [17]:
df['last_review'] = pd.to_datetime(df['last_review'])

# Convertir booleanos

In [21]:
df['instant_bookable'] = df['instant_bookable'].map({'TRUE': 1, 'FALSE': 0})

# Rellenamos valores vacios

In [22]:
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)

# Eliminar columnas que no nos sirven

In [29]:
df = df.drop(columns=['license', 'house_rules','country'])

# Convertir columnas numericas

In [24]:
cols = [
    'minimum_nights',
    'number_of_reviews',
    'reviews_per_month',
    'review_rate_number',
    'calculated_host_listings_count',
    'availability_365'
]

df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   name                            102349 non-null  object
 2   host_id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host_name                       102193 non-null  object
 5   neighbourhood_group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country_code                    102468 non-null  object
 10  instant_bookable                0 non-null       float64
 11  cancellation_policy             102523 non-null  object
 12  room_type                       102599 non-null  object
 13  construction_year               102385 non-null  float64
 14  price                           102352 non-null  float64
 15  service_fee                     102326 non-null  float64
 16  minimum_nights                  102190 non-null  float64
 17  number_of_reviews               102416 non-null  float64
 18  last_review                     86706 non-null   datetime64[ns]
 19  reviews_per_month               102599 non-null  float64
 20  review_rate_number              102273 non-null  float64
 21  calculated_host_listings_count  102280 non-null  float64
 22  availability_365                102151 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(2), object(8)
memory usage: 18.0+ MB

In [31]:
df['room_type'].value_counts()

room_type
Entire home/apt    53701
Private room       46556
Shared room         2226
Hotel room           116
Name: count, dtype: int64

# Guardar dataframe limpio

In [32]:
df.to_csv('airbnb_limpio.csv', index=False)

In [33]:
from google.colab import files
files.download('airbnb_limpio.csv')